[theme]
base = "dark"
primaryColor = "#FFD700"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#111111"
textColor = "#FFFFFF"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 10

[browser]
gatherUsageStats = false
serverAddress = "mundial2026-loschangos.streamlit.app"
serverPort = 443
