# ======================
# GOOGLE OAUTH (streamlit-oauth)
# ======================
GOOGLE_CLIENT_ID = "1037333463143-52cjku9lj9fk0v0ms48lmoegno8v948v.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI = "https://mundial2026-loschangos.streamlit.app"

# ======================
# GOOGLE SHEETS (Service Account)
# ======================
SHEET_ID = "1wYyNub3z4gBD4IIvdHaEo3PsLYJDJrp6UBFxuYmV4IM"

GCP_SERVICE_ACCOUNT = """
{
  "type": "service_account",
  "project_id": "prode-mundial-2026-498201",
  "private_key_id": "61b4cb46e06f8f0a4c48b92563486d87e684d9d8",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDQkxVZKkCyDUmg\nUqazgTU+9e+mj1HSZvih1DzRFB8NpnMKzD5AlHXUd4GuIUwx7BHtfTaePZDLOgZQ\nQNSpamWGKx8Y308na0OWOX5ZwfDF25DUqWI55Ia5pVKlG6vBbOySe4Fi1JrGBp/9\n3ruLylxR67ww3WVO0HRYptmyLjSgrvqv9NTbsTPj4A9UwD8cIe36zWgo+t6Vphq3\npXWEI9MiEsyIfNDVnuhxuJ68r9ymE4YGMASBfvEO+jF3Dwnz5SoSdl1QFFNLyWPO\nk+RI8vX84OgGL5RgCa0K5EOwqnaME8eFlxdfaQwm356HqZdf7hFDVgAIAzmjM12N\naDFB7N/pAgMBAAECggEAArVBXzPlvPB504uPLFOrcDXuo4Z6PpWYrJ03uiBqDZoE\njCmkgaxYlUzrhNCPQsyr9Oq3XuzLG8bIMADCruQGdAX/56l3YSC+GWeFfovYLb5E\nJ9N+xrEMlyd22bu9ij7ff9ou28YjFk23hESajpEuvqxYkd4/nPtAfENguAGfX4Cw\nGHBODIGKhP4cnnN48ufOueon9htbkhBf1mdD5WTL+sAXWIDOqbUcNuT8x85UtrEr\nB/2zLM+8ZF4VIXpmVyoQ9StIm5lWW5CzwBMur+FT0A3zuyMyGGv/yeSiYdQs9vlJ\nNE2Hbdw4my7LfcARvwvsmbNAn7vqeaX9Z5FpW/7bGwKBgQDtti7np1HKNHrz0UmQ\nME/IRAoSxVYXe2vxoatVUrS51Trwzm4SZiVnShrqgnGh+E0DcRiwGxwqtk58HVDA\nWLav+clJKK3JSO9tI458DmOJcwYMJ+2TpMpELxtEih1SMmlQo9u/byDNybgqvSfL\nTXeTZ0qwS69gLcl3WrBpOLAFBwKBgQDgnwjH7M034gzNXKAch8THmVB5JG18ojOS\nPgzt9lFKt4lGgMIgJlBmlmvjtHK5F6cfpHxWgKW+pLSGKGS3bhxrOS+32x6WQVoI\nufbETXMlPZkYfoRNUxeiDc+XyXLRoSof/1OCAHQHTkLl+63YAurZbu/tFqIR2aPU\nGWF8svonjwKBgGT7rSdqFDvjWYw0j5y6eVopVWIuBOnK28t1k7SWgwIjDHv6JhaY\n4DDl8VNIgP9+3TCmHgfKLIgUlHjzdzePOGS/p3v11QYafuQNY91du3lLrPkDCVFc\ngzS+EkZmqhgeJFFGmvbTPctOc3dsjfg2+6JaEgecz277ZIfYtfKtS1GHAoGARZmh\nq+k5MY6urtd7mTuMgtiDsfXSoyLTXgYyFW4UhFVYiOsOu82DbjY/2f+o6Kdmloxu\nJpOYR/lbIpLTmm7ZCXRfz9Vqpd48GqYcy3jALBLpJEjXj+omUYV8BKlcFY6dsep4\norinOzhJzF9u35cP1C3m1A0GTQemFuuCZJREpQsCgYAgi6q2IYaL32XWT91gDw/l\nHjJoHvjQM5DApB6kARf9p6sZXYcyCkO8WN6gK/YJNjJgf13xyjTU/QhEkkH7LqyL\nX3AVoA2pyNA1SmdF2gKvuZ8fFwukG4rUMWQae1YSc58QVX06/Zds9FUrL9+Zx5Cy\nWisIkMGu4hwiCN8UMM2Nvw==\n-----END PRIVATE KEY-----\n",
  "client_email": "prodemundial2026@prode-mundial-2026-498201.iam.gserviceaccount.com",
  "client_id": "104234662021922248386",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/prodemundial2026%40prode-mundial-2026-498201.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
