# ======================
# GOOGLE OAUTH (streamlit-oauth)
# ======================
GOOGLE_CLIENT_ID = "1037333463143-52cjku9lj9fk0v0ms48lmoegno8v948v.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI = "https://mundial2026-loschangos.streamlit.app"

# ======================
# GOOGLE SHEETS (Service Account)
# ======================
SHEET_ID = "1wYyNub3z4gBD4IIvdHaEo3PsLYJDJrp6UBFxuYmV4IM"

GCP_SERVICE_ACCOUNT = """
{
  "type": "service_account",
  "project_id": "tu-proyecto",
  "private_key_id": "xxxxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\nTU-CLAVE-PRIVADA-AQUI\n-----END PRIVATE KEY-----\n",
  "client_email": "tu-service-account@tu-proyecto.iam.gserviceaccount.com",
  "client_id": "xxxxxxxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token"
}
"""
