[auth]
redirect_uri = "https://mundial2026-loschangos.streamlit.app/oauth2callback"
cookie_secret = "prode-mundial-2026-super-secret-random-string-2026-xxxx"

[auth.google]
client_id = "1037333463143-52cjku9lj9fk0v0ms48lmoegno8v948v.apps.googleusercontent.com"
client_secret = "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"
